site_name: OSCP Notes
site_url: https://daniel-britt.github.io/OSCP-Notes/
site_author: Daniel Britt
site_description: Notes and resources for preparing to take the OSCP exam.
copyright: 2019 by Daniel Britt
theme: slate

nav:
  - 'Useful Links': 'useful links.md'
  - 'Enumeration': 'enumeration.md'
  - 'Shells': 'shells.md'
  - Tools:
    - 'Tools': 'tools.md'
    - 'Netcat': 'tools/netcat.md'
  - 'About': 'about.md'